Ingredient.create(name: "もやし", average_price: 30)
Ingredient.create(name: "鶏むね肉", average_price: 150)
Ingredient.create(name: "キャベツ", average_price: 100)
Ingredient.create(name: "玉ねぎ", average_price: 80)
Ingredient.create(name: "にんじん", average_price: 60)